### ISSUE TITLE
昨晚发现脚本被清空，拉不上库。

### ISSUE THREAD

**Issue by axieshi** [shufflewzc/fakergone#118]
fatal: No such remote 'origin'
fatal: Updating an unborn branch with changes added to the index.
## 开始执行... 2021-10-03 07:46:06
--------------------------------------------------------------
## 开始执行... 2021-10-03 07:46:07
开始更新仓库：/ql/repo/shufflewzc_faker2
更新/ql/repo/shufflewzc_faker2成功...

**Comment by shufflewzc** [comment]
重新拉遍
