### ISSUE TITLE
京东资产变动无通知（企业微信）

### ISSUE THREAD

**Issue by muzi13** [shufflewzc/fakergone#132]
日志如下：

## 开始执行... 2021-10-11 12:42:39

🔔京东资产变动, 开始!

====================共8个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021/10/11 下午12:42:39=====================

******开始查询【京东账号1】334294291-186627*********

正在获取领现金任务签名...
领现金任务签名获取成功...
【账号1🆔】勾**
【账号信息】🥇金牌Plus,京享值7219
【今日京豆】收272豆,支5豆
【昨日京豆】收110豆,支5豆
【当前京豆】18264豆(≈182.64元)
【京喜牧场】320枚鸡蛋
【极速金币】583974币(≈58.40元)
【京东赚赚】285800币(≈28.58元)
【京东秒杀】7282币(≈7.28元)
【其他信息】汪汪:1级,领现金:29.16元
【东东农场】20包湿巾(51%,26天)
【京喜工厂】维达手帕纸(30%,6天)
【东东工厂】vivo iQOO入耳式耳机(57%,剩193)
【东东萌宠】3层抽纸巾30包(76%,1/4块)
🧧🧧🧧红包明细🧧🧧🧧
【红包总额】6.12(总过期0.64)元 
【京喜红包】3.72(将过期0.10)元 
【京东红包】2.40(将过期0.54)元 
。。。。。。
。。。。。。

text.content exceed max length 5120. Invalid input invalid Request Parameter, hint: [***********_233_b5967264102cf45c1b21caa442aca42b], from ip: 117.176.190.***, more info at https://open.work.weixin.qq.com/devtool/query?e=40058

企业微信发送通知消息成功🎉。

🔔京东资产变动, 结束! 🕛 192.033 秒

**Comment by shufflewzc** [comment]
其他脚本有没有

**Comment by xjzyy** [comment]
我有3个账号，第三个每次资产变动通知就显示不全，这是bug吗？

**Comment by muzi13** [comment]
> 其他脚本有没有

其他脚本通知正常

**Comment by shufflewzc** [comment]
@muzi13 脚本文件名称是？

**Comment by xjzyy** [comment]
> 其他脚本有没有

大佬 这个情况正常吗

**Comment by muzi13** [comment]
> @muzi13 脚本文件名称是？

jd_bean_change.js和jd_bean_change_new.js

**Comment by xjzyy** [comment]
@muzi13 你京豆怎么这么多，我每次都几十个

**Comment by muzi13** [comment]
@xjzyy 我这有几个号也就七八十个豆。

**Comment by xjzyy** [comment]
🔔宠汪汪积分兑换有就换版, 开始!
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module './utils/JDJRValidator_Pure'
Require stack:
- /ql/scripts/shufflewzc_faker2_jd_joy_reward_Mod.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/ql/scripts/shufflewzc_faker2_jd_joy_reward_Mod.js:7:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/scripts/shufflewzc_faker2_jd_joy_reward_Mod.js' ]
}
更新任务状态成功

执行结束...

**Comment by muzi13** [comment]
@shufflewzc 京东月资产变动通知脚本jd_all_bean_change.js可以正常通知。

**Comment by muzi13** [comment]
@xjzyy 检查一下：
ql repo https://ghproxy.com/https://github.com/shufflewzc/faker2.git "jd_|jx_|gua_|jddj_|getJDCookie" "activity|backUp" "^jd[^_]|USER|function|utils|ZooFaker_Necklace.js|JDJRValidator_Pure|sign_graphics_validate|ql"

**Comment by xjzyy** [comment]
开始执行... 2021/10/11 下午4:38:34

--------------------------------------------------------------

开始更新仓库：/ql/repo/shufflewzc_faker2

Fetching origin
warning: redirecting to https://github.com.cnpmjs.org/shufflewzc/faker2.git/
From https://ghproxy.com/https://github.com/shufflewzc/faker2
   5feb7fb..bfff082  main       -> origin/main
HEAD is now at 5feb7fb update
warning: redirecting to https://github.com.cnpmjs.org/shufflewzc/faker2.git/
Updating 5feb7fb..bfff082
Fast-forward
 JS_USER_AGENTS.js                                  |  154 +-
 USER_AGENTS.js                                     |   72 +-
 .../jd_car_exchange_xh.js                          |    0
 backUp/jd_joy_reward_Mod.js                        | 1140 +++++++++++
 jd_live_redrain.js => backUp/jd_live_redrain.js    |    0
 .../jd_priceProtect_Mod.js                         |    0
 gua_opencard43.js                                  |  144 ++
 jd_DailyBonus_Mod.js                               | 2025 ++++++++++++++++++++
 jd_bean_change.js                                  |    4 +-
 jd_beauty_twelfth.js                               |   24 +
 jd_car_exchange.js                                 |  374 ++++
 jd_dddh.js                                         |  220 +++
 jd_dpqd_diy.js                                     |    7 +-
 jd_fansa.js                                        |   22 +-
 jd_gold_creator.js                                 |   28 +
 jd_haier.js                                        |  509 +++++
 jd_joy_reward_Mod.js                               |    6 +-
 jd_lzdz1_jq.js                                     |  556 ++++++
 jd_price.js                                        |  274 +++
 jd_sendBeans.js                                    |   63 +-
 package.json                                       |   23 +-
 sendNotify.js                                      |  216 ++-
 22 files changed, 5635 insertions(+), 226 deletions(-)
 rename jd_car_exchange_xh.js => backUp/jd_car_exchange_xh.js (100%)
 create mode 100644 backUp/jd_joy_reward_Mod.js
 rename jd_live_redrain.js => backUp/jd_live_redrain.js (100%)
 rename jd_priceProtect_Mod.js => backUp/jd_priceProtect_Mod.js (100%)
 create mode 100644 gua_opencard43.js
 create mode 100644 jd_DailyBonus_Mod.js
 create mode 100644 jd_beauty_twelfth.js
 create mode 100644 jd_car_exchange.js
 create mode 100644 jd_dddh.js
 create mode 100644 jd_haier.js
 create mode 100644 jd_lzdz1_jq.js
 create mode 100644 jd_price.js

更新/ql/repo/shufflewzc_faker2成功...

检测到有失效的定时任务：

shufflewzc_faker2_jd_car_exchange_xh.js
shufflewzc_faker2_jd_live_redrain.js
shufflewzc_faker2_jd_priceProtect_Mod.js

开始尝试自动删除失效的定时任务...

成员ID:@all企业微信应用消息发送通知消息成功🎉。

检测到有新的定时任务：

shufflewzc_faker2_jd_beauty_twelfth.js
shufflewzc_faker2_jd_DailyBonus_Mod.js
shufflewzc_faker2_jddj_bean.js
shufflewzc_faker2_jd_price.js
shufflewzc_faker2_gua_MMdou.js
shufflewzc_faker2_jd_lzdz1_jq.js
shufflewzc_faker2_jd_haier.js
shufflewzc_faker2_gua_wealth_island_help.js
shufflewzc_faker2_gua_UnknownTask3.js
shufflewzc_faker2_jddj_plantBeans.js
shufflewzc_faker2_jddj_fruit.js
shufflewzc_faker2_jd_delCoupon.js
shufflewzc_faker2_gua_ddgame.js
shufflewzc_faker2_jddj_fruit_collectWater.js
shufflewzc_faker2_gua_wealth_island.js
shufflewzc_faker2_gua_opencard43.js
shufflewzc_faker2_jd_car_exchange.js
shufflewzc_faker2_jd_dddh.js
shufflewzc_faker2_jddj_getPoints.js

开始尝试自动添加定时任务...

美妆周年庆 -> 添加成功
jd_DailyBonus_Mod.js -> 添加成功
jddj_bean.js -> 添加成功
京东保价 -> 添加成功
MM领京豆 -> 添加成功
金秋好物盛典 福利来袭 -> 添加成功
瓜分海尔万元小家电 -> 添加成功
财富大陆互助 -> 添加成功
寻找内容鉴赏官 -> 添加成功
jddj_plantBeans.js -> 添加成功
jddj_fruit.js -> 添加成功
删除优惠券 -> 添加成功
东东游戏 -> 添加成功
jddj_fruit_collectWater.js -> 添加成功
财富大陆 -> 添加成功
10.11~10.26 惠聚京东 好物连连 -> 添加成功
京东汽车兑换 -> 添加成功
东东世界兑换 -> 添加成功
jddj_getPoints.js -> 添加成功
成员ID:@all企业微信应用消息发送通知消息成功🎉。


执行结束...

**Comment by muzi13** [comment]
今天更新了脚本，但还是老样子，运行jd_bean_change.js后，资产变动无通知，只有京东白嫖榜的通知。
