### ISSUE TITLE
签到领现金通知有问题

### ISSUE THREAD

**Issue by xinchenjingtu** [shufflewzc/fakergone#152]
shufflewzc_faker2_jd_cash.js 文件中，第146行，这个判断永远进不来，allMessage 永远为空，导致通知永远不会发送。
![image](https://user-images.githubusercontent.com/31204263/138625465-54bb2360-e62b-42c7-80c1-abf86f05f8b6.png)

**Comment by shufflewzc** [comment]
稍后修复
