### ISSUE TITLE
为什么多个脚本运行时都不是自己的帐号？

### ISSUE THREAD

**Issue by design-1996** [shufflewzc/fakergone#153]
东东萌宠等N个脚本运行时都为 jd_4609829ba8aca   这个帐号。不是自己的帐号，只有几个脚本运行时 是自己的帐号。我还特地去京东看了，并没有做任务。这是挂着服务器帮别人做？

**Comment by shufflewzc** [comment]
怎么可能

**Comment by design-1996** [comment]
> 怎么可能

确实是这样。我在定时任务里面添加青龙的拉取脚本，然后在环境变量添加JD_COOKIE 里面填入自己的cookie。然后我就执行脚本，就出现这种情况。

**Comment by design-1996** [comment]
![image](https://user-images.githubusercontent.com/66763836/138667934-f0920261-e082-47cb-b62d-8727a8c640b5.png)

**Comment by design-1996** [comment]
别人的帐号

**Comment by design-1996** [comment]
重启正常了
