### ISSUE TITLE
12个账号 资产变动脚本电报发不出去通知：

### ISSUE THREAD

**Issue by MagnusWTC** [shufflewzc/fakergone#185]
12个账号 资产变动脚本电报发不出去通知：
脚本：jd_bean_change_new
报错：telegram发送通知消息失败！！

HTTPError: Response code 400 (Bad Request)
    at Request.<anonymous> (/ql/scripts/node_modules/.pnpm/got@11.8.2/node_modules/got/dist/source/as-promise/index.js:117:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: undefined,
  timings: {
    start: 1636903958534,
    socket: 1636903958535,
    lookup: 1636903958535,
    connect: 1636903958537,
    secureConnect: 1636903959357,
    upload: 1636903959358,
    response: 1636903959926,
    end: 1636903959926,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 0,
      tcp: 2,
      tls: 820,
      request: 1,
      firstByte: 568,
      download: 0,
      total: 1392
    }
  }
}

猜测可能是http报文体过长，电报对其进行了限制，建议作者账号太多进行优化，可以分几次发送

**Comment by 592732377** [comment]
sendNotify.js 详细说明参考 https://github.com/ccwav/QLScript2.  第3条和5条。
