### ISSUE TITLE
京东试用报错，返回一个页面内容导致JSON解析失败

### ISSUE THREAD

**Issue by NicolasLi-CN** [shufflewzc/fakergone#19]
上周三左右开始出现的这个问题
怀疑是请求频率的问题，或者可能跟UserAgent有关
会返回一个title为 “多快好省，购物上京东！”的页面
我自己这里在getGoodListByCond和isFollowed方法里的请求出现过这个问题

我尝试使用我浏览器的UA和 使用其他脚本看到的使用随机UA的办法（'UserAgent': $.isNode() ? (process.env.JD_USER_AGENT ? process.env.JD_USER_AGENT : (require('./USER_AGENTS').USER_AGENT)) : ($.getdata('JDUA') ? $.getdata('JDUA') : "jdapp;iPhone;9.4.4;14.3;network/4g;Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148;supportJDSHWK/1")）
依然会出现错误

希望大佬有空的时候看一下，感谢shuffle大佬！！

**Comment by shufflewzc** [comment]
@koraLi 确实是调用频率问题，可以尝试修改试用的环境变量换些类目

**Comment by shufflewzc** [comment]
已经修复
