### ISSUE TITLE
请问大佬 助力池现在是怎么解决

### ISSUE THREAD

**Issue by umbrellax** [shufflewzc/fakergone#191]
提交在zero0的助力池机器人里 检测到没跑他的脚本就给我黑号了 无法提交助力池了 蓝瘦

**Comment by shufflewzc** [comment]
我的不是zero那个助力池 是jdsharecodebot

**Comment by umbrellax** [comment]
> 我的不是zero那个助力池 是jdsharecodebot

我的意思是跑你的脚本 助力池不是要还是在那提交嘛 但是他会检测跑的是不是他的  现在没有助力了 大佬能做个助力池吗
