### ISSUE TITLE
faker2里面配置脚本有问题吧

### ISSUE THREAD

**Issue by jackblackjjx** [shufflewzc/fakergone#194]
faker2执行多合一脚本的时候，提示JD_DailyBonus,js文件不存在，但是faker3里面的才是JD_DailyBonus.js
就拉一个faker2的库，faker2里面的是 jd_DailyBonus_Mod.js,你修改版的请求重制版的？！！！

**Comment by shufflewzc** [comment]
我2个都有吧应该
