### ISSUE TITLE
京喜红包任务不会自动停止

### ISSUE THREAD

**Issue by linyongfu2013** [shufflewzc/fakergone#202]
![image](https://user-images.githubusercontent.com/4011963/143970413-346dd3c6-4de5-4eae-bf01-6f7254820eb0.png)

**Comment by linyongfu2013** [comment]
送豆得豆也是

**Comment by shufflewzc** [comment]
你这个属于号太多，云服务器配置太低的原因

**Comment by linyongfu2013** [comment]
才10个号，2核4G 还低？

**Comment by shufflewzc** [comment]
那应该是脚本问题了
