### ISSUE TITLE
京东多合一签到出错

### ISSUE THREAD

**Issue by ghost** [shufflewzc/fakergone#203]
提示：JD_DailyBonus.js 文件不存在，停止执行京东多合一签到

**Comment by shyg866** [comment]
我的也是，重拉了一次代码就废了

**Comment by shyg866** [comment]
找到解决办法了,把“/docker/ql/repo/shufflewzc_faker2/utils/JD_DailyBonus.js” 复制到“/docker/ql/scripts/shufflewzc_faker2/utils”下面就行了。

**Comment by creazy412** [comment]
> 找到解决办法了,把“/docker/ql/repo/shufflewzc_faker2/utils/JD_DailyBonus.js” 复制到“/docker/ql/scripts/shufflewzc_faker2/utils”下面就行了。

黑群晖上跑的docker，环境不一致吗？没找到 “/docker/ql/repo/shufflewzc_faker2” 这目录呢

**Comment by shyg866** [comment]
邮件已收到，我会尽快回复！祝你身体健康,事业有成.
