### ISSUE TITLE
sendNotify.js 拉取不了最新的

### ISSUE THREAD

**Issue by MapleRedbean** [shufflewzc/fakergone#204]
sendNotify.js 拉取不了最新的，每次拉下来都是没有备注的版本，但是实际项目里是有备注的版本的，

**Comment by shufflewzc** [comment]
你拉库命令错了应该 关注tg群的拉库命令

**Comment by MapleRedbean** [comment]
> 你拉库命令错了应该 关注tg群的拉库命令
应该不会啊，你们每天都更新通知，我每次也是复制最后一个的。我现在复制到desp了，算了
