### ISSUE TITLE
报告2个jd_disable.py的bug

### ISSUE THREAD

**Issue by jjj333** [shufflewzc/fakergone#205]
我直接运行拉取的文件运行报key err:'name'
看了一下代码，修改了两处：
1、url变量内的端口写死5700了，自定义端口的可能就不适用，才疏学浅的我只会手动改成我自定义的端口。。。。。。。。
2、所有元素的取值方法——['name']，我都改成了.get('name')

然后就能运行了

PS：奇怪的是原版下我print了taskList和task['name']，都能正确打印，但最终运行结果就是报错

**Comment by shufflewzc** [comment]
是什么版本的青龙呢？

**Comment by jjj333** [comment]
当前最新的2.10.10

**Comment by shufflewzc** [comment]
你把脚本前缀也加上

**Comment by ghost** [comment]
更新了

https://github.com/Oreomeow/VIP/blob/main/Scripts/py/disable.py

**Comment by jjj333** [comment]
啊，太感谢了！
