### ISSUE TITLE
拉取问题

### ISSUE THREAD

**Issue by bigcat11** [shufflewzc/fakergone#206]
为啥我拉去库中的sendNoity这个库和github库中的sendNoity的内容不一样，试了好几次

**Comment by cncherisher** [comment]
遇到同样问题，ql repo拉库之后，sendnotify.js就被重置成青龙自带的800多行的版本，没有自动更新wskey的功能了
https://github.com/whyour/qinglong/commit/31cd7c4007c14f745c823694a2ec2aaa4df7ec78#commitcomment-60215885
应该是上游问题，临时解决办法是降级到到2.10.6及之前的版本
