### ISSUE TITLE
资产变动通知BUG

### ISSUE THREAD

**Issue by yzqiang666** [shufflewzc/fakergone#208]

**Comment by yzqiang666** [comment]
由于tg bot api限制，文本超过4096时发送通知消息错误，返回400，因此账户大约超过10个时通知错误。
能否修改为每10个账户发送一次通知，这样分批发送可以避免错误。

已解决了：
在config.sh中加入： BEANCHANGE_PERSENT="10"
即可按每10个账户发送通知。

**Comment by jmpoep** [comment]
❌ 京东资产变动通知, 失败! 原因: TypeError: Cannot read properties of undefined (reading 'length')!
