### ISSUE TITLE
您好，麻烦请教一下

### ISSUE THREAD

**Issue by kikispenser** [shufflewzc/fakergone#210]
用的青龙面板最新的，其中多合一有点问题 麻烦您给看一下 提示

“Faker 友情提示：您的脚本正常运行中

JD_DailyBonus.js 文件不存在，停止执行京东多合一签到”

请问一下这个怎么解决，谢谢

**Comment by shyg866** [comment]
找到解决办法了,把“/docker/ql/repo/shufflewzc_faker2/utils/JD_DailyBonus.js” 复制到“/docker/ql/scripts/shufflewzc_faker2/utils”下面就行了。
