### ISSUE TITLE
请更新下function和utils下的sendnotify.js

### ISSUE THREAD

**Issue by cncherisher** [shufflewzc/fakergone#225]
由于青龙那边的问题，ql repo更新仓库会导致仓库根目录下的sendnotify.js被覆盖，使得自动更新wskey的功能失效
https://github.com/whyour/qinglong/commit/31cd7c4007c14f745c823694a2ec2aaa4df7ec78#commitcomment-60215820
#204
#206
都是类似的问题

**Comment by shufflewzc** [comment]
好的
