### ISSUE TITLE
发现了挖矿病毒

### ISSUE THREAD

**Issue by heyXiaoT** [shufflewzc/fakergone#227]
在两台服务器里面安装了，都提示有挖矿病毒……

**Comment by shufflewzc** [comment]
哪个脚本

**Comment by heyXiaoT** [comment]
> 哪个脚本

不知道，只是怀疑是脚本的问题；我这边两台服务器在上上周装了青龙面板和京东脚本，这几天都发现了挖矿病毒。
![image](https://user-images.githubusercontent.com/30957584/145716437-38fd75f0-92e7-4987-bab8-f24a6a748e36.png)
![image](https://user-images.githubusercontent.com/30957584/145716477-fac0efd1-f645-4bb0-b309-6d51d259f7ba.png)

这两台服务器我都用了大半年了，这几天都出现了同样的情况；现在怀疑是面板或脚本的问题。

阿里云是上12月4号被异地登录，12月6号发现了挖矿病毒，后续我进行了杀进程和删除文件的操作，12月7号又提示发现了病毒； 腾讯云是12月11号发现了挖矿病毒，同样我也进行了杀进程和删除文件的操作。

两个平台内部的详细信息都是是 /var/tmp/.crypto/.../httpd 和 /var/tmp/.../httpd-w 有病毒。

**Comment by shufflewzc** [comment]
你是不是只使用青龙的

**Comment by xjzyy** [comment]
这么可怕吗
