### ISSUE TITLE
问一个关于自动更新config.sh的问题

### ISSUE THREAD

**Issue by Eva-Joker** [shufflewzc/fakergone#233]
https://raw.githubusercontents.com/shufflewzc/VIP/main/Conf/Qinglong/config.sample.sh

通过这个网址直接点进去，看到的是3.0.0版本
为何执行curl -L https://raw.githubusercontents.com/shufflewzc/VIP/main/Conf/Qinglong/config.sample.sh -o /ql/sample/config.sample.sh && cp -rf /ql/sample/config.sample.sh /ql/config后，获得的config.sample.sh依旧是2.8.0版本。

很是不理解，有大佬可以解释一下吗？

**Comment by shufflewzc** [comment]
目测是没有更换成功。。可能是shell有问题

**Comment by Eva-Joker** [comment]
今天扫了一眼，同步成功，已解决，关闭问题。
