### ISSUE TITLE
“更新/ql/repo/shufflewzc_faker2失败”  如何解决？？？

### ISSUE THREAD

**Issue by zhaoyong0317** [shufflewzc/fakergone#235]
## 开始执行... 2021-12-17 17:34:58

开始克隆仓库 https://ghproxy.com/https://github.com/shufflewzc/faker2.git 到 /ql/repo/shufflewzc_faker2

更新/ql/repo/shufflewzc_faker2失败，重新下载全新仓库...

开始克隆仓库 https://ghproxy.com/https://github.com/shufflewzc/faker2.git 到 /ql/repo/shufflewzc_faker2

更新/ql/repo/shufflewzc_faker2失败，请检查网络...

## 执行结束... 2021-12-17 17:35:08  耗时 10 秒

请问 这个问题如何解决？？？

**Comment by Eva-Joker** [comment]
github连接不稳定。

**Comment by spiderkkk** [comment]
怎么解决这个问题？？？？

**Comment by shufflewzc** [comment]
请检查网络...或者加减代理头
