### ISSUE TITLE
“批量取关店铺和商品”脚本问题

### ISSUE THREAD

**Issue by XXIN0** [shufflewzc/fakergone#236]
环境变量已经按照注释更改，但是脚本现在无法正常运行
![image](https://user-images.githubusercontent.com/41498132/146642489-d2f1bd5e-a659-49fb-b3b0-2e62cb4cae78.png)

**Comment by qsjc** [comment]
我也遇到这个错误了

**Comment by XXIN0** [comment]
问题作者已修复，故关闭
