### ISSUE TITLE
签到领现金 疑似api问题

### ISSUE THREAD

**Issue by trytrytogo** [shufflewzc/fakergone#243]
使用faker2的最新的库，执行签到领现金任务，出现
"Timeout awaiting 'request' for 30000ms"
签到领现金 getSign API请求失败，请检查网路重试

我找了接口，IP是正常的。没看出其他啥问题。

**Comment by trytrytogo** [comment]
尝试了家宽以及机房内的服务器，均是这个情况

**Comment by shufflewzc** [comment]
目测是并发太多的问题，需要减少并发任务数量

**Comment by trytrytogo** [comment]
> 目测是并发太多的问题，需要减少并发任务数量

家宽，并未开启并发，也有这个情况。   我看了下，脚本中，未发现有设置延迟的变量，可还有其他办法？
