### ISSUE TITLE
东东小窝 api异常

### ISSUE THREAD

**Issue by trytrytogo** [shufflewzc/fakergone#244]
东东小窝 API请求失败，请检查网路重试
"getaddrinfo ENOTFOUND lkyl.dianpusoft.cn"

经测试，无法解析出此域名的IP。
https://s2.loli.net/2021/12/21/1X63MCRPhBIjKF2.jpg
![FCkdR292S6mMLeZ.jpg](https://s2.loli.net/2021/12/21/1X63MCRPhBIjKF2.jpg)

**Comment by shufflewzc** [comment]
收到，感谢反馈
