### ISSUE TITLE
JD_DailyBonus.js这个文件手动添加也会提示下载异常

### ISSUE THREAD

**Issue by timeless07** [shufflewzc/fakergone#25]
![image](https://user-images.githubusercontent.com/22607017/127969115-a54520f9-c683-4109-a631-b0c37d57195a.png)
JD_DailyBonus.js 文件不存在，停止执行京东多合一签到

成员ID:@all企业微信应用消息发送通知消息成功🎉。

🔔京东多合一签到, 结束! 🕛 0.534 秒

## 执行结束... 2021-08-03 14:34:41  耗时 1 秒

**Comment by timeless07** [comment]
![image](https://user-images.githubusercontent.com/22607017/127969244-9c317860-1d5d-4a06-8a98-cb804bbdd4b2.png)

**Comment by coppea** [comment]
使用A1，脚本库是这个，也是这个错误

**Comment by shufflewzc** [comment]
进TG群查看脚本依赖修复教程 谢谢

**Comment by Rosylusi** [comment]
> 进TG群查看脚本依赖修复教程 谢谢

tg群进不去，能麻烦在这边发一下教程吗？谢谢

**Comment by tanst** [comment]
放到 scripts/utils/ 目录下试试？
