### ISSUE TITLE
寻找组织

### ISSUE THREAD

**Issue by LSydLee** [shufflewzc/fakergone#257]
请问怎么样才能找到组织一起交流？

**Comment by shufflewzc** [comment]
看readme

**Comment by LSydLee** [comment]
没有找到群号码喔~ 以前看到的QQ群号码，都搜索不到了



在 2022-01-07 15:00:48，"Faker" ***@***.***> 写道：

Closed #257.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
