### ISSUE TITLE
炸年兽

### ISSUE THREAD

**Issue by HD12138** [shufflewzc/fakergone#263]
大锅炸年兽还搞不

**Comment by shufflewzc** [comment]
已经上线了啊

**Comment by HD12138** [comment]
好的 看见了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月9日(星期天) 晚上6:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [shufflewzc/faker2] 炸年兽 (Issue #263)





 
已经上线了啊
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by verages** [comment]
炸年兽不能助力是为啥

**Comment by shufflewzc** [comment]
> 炸年兽不能助力是为啥

因为现在这个脚本暂时不行

**Comment by HD12138** [comment]
不清楚




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月10日(星期一) 中午11:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [shufflewzc/faker2] 炸年兽 (Issue #263)





 
炸年兽不能助力是为啥
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HD12138** [comment]
坐等大佬更新




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月10日(星期一) 中午11:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [shufflewzc/faker2] 炸年兽 (Issue #263)





 
炸年兽不能助力是为啥
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
