### ISSUE TITLE
是否有脚本试图盗取账号信息

### ISSUE THREAD

**Issue by Madao1994** [shufflewzc/fakergone#266]
请问这些脚本是大佬自己写的吗，还是从其他地方汇总来的，我发现我的青龙面板每天都有登录失败的记录，登录地址是114.55.35.86，一个阿里云的地址

**Comment by 1486308032** [comment]
一堆扫端口的，很正常。把端口改一下，别用80，ssh也禁用密码登录，改用密钥登陆
