### ISSUE TITLE
脚本跑了十个账号就停止了

### ISSUE THREAD

**Issue by ericting** [shufflewzc/fakergone#28]
rt，好多脚本都有类似的问题
![image](https://user-images.githubusercontent.com/29013507/128115806-c877c6ea-da5e-4578-b9fa-d910f9edc906.png)
像这个，容器里20多个账号，才跑了一半

**Comment by ericting** [comment]
![image](https://user-images.githubusercontent.com/29013507/128115895-a1ef9128-0ada-4584-869b-c652aa177712.png)
不好意思发了个过期了的截图

**Comment by shufflewzc** [comment]
可能是配置问题，查看你的config.sh
