### ISSUE TITLE
大佬能不能出个云函数版本

### ISSUE THREAD

**Issue by Pessimisticc** [shufflewzc/fakergone#30]
吊大的大佬能不能出个云函数版本！！

**Comment by zero205** [comment]
> 吊大的大佬能不能出个云函数版本！！

我的仓库主打云函数

**Comment by Pessimisticc** [comment]
> > 吊大的大佬能不能出个云函数版本！！
> 
> 我的仓库主打云函数

我用过你的，但是好像不能自己获取互助吗，均等互助吧，得手动设置邀请码环境

**Comment by shufflewzc** [comment]
https://github.com/zero205/JD_tencent_scf
