### ISSUE TITLE
TG群怎么加不了？

### ISSUE THREAD

**Issue by Rosylusi** [shufflewzc/fakergone#37]

**Comment by shufflewzc** [comment]
Tg群看不到办法：
1、登录web.telegram.org网站
2、点击(settings/设置)
3、点击 show sensitive Content
4、打开 Disable filtering
5、设置完成重启app客户端

**Comment by Rosylusi** [comment]
大佬你好，我这好像没有show sensitive Content选项
![微信截图_20210811111054](https://user-images.githubusercontent.com/43165837/128963716-7c2ceece-2edb-456a-9091-1cdacc224153.png)

**Comment by WindStill** [comment]
设置完了，还是搜不到群

**Comment by zijianrs** [comment]
> 大佬你好，我这好像没有show sensitive Content选项
> ![微信截图_20210811111054](https://user-images.githubusercontent.com/43165837/128963716-7c2ceece-2edb-456a-9091-1cdacc224153.png)

1. Login  web.telegram.org

2. Change to old version
![image](https://user-images.githubusercontent.com/89035011/130565729-0392ba4b-6672-4227-b0e8-98c81d05970d.png)

**Comment by StupidAssjeff** [comment]
??

**Comment by StupidAssjeff** [comment]
??

**Comment by creazy412** [comment]
TG 番号？？多谢
