### ISSUE TITLE
jd_bean_sign.js脚本跑起来，提示JD_DailyBonus.js 文件不存在，停止执行京东多合一签到

### ISSUE THREAD

**Issue by DingChang90** [shufflewzc/fakergone#39]
jd_bean_sign.js脚本跑起来，提示JD_DailyBonus.js 文件不存在，停止执行京东多合一签到

**Comment by ChellyL** [comment]
老哥你依赖没装完，看这个：
https://thin-hill-428.notion.site/QL-pannel-Dependent-Librai-164400378c7f4a4587f976e89aea1584

进容器 docker exec -it qinglong bash 然后 cd qinglong/scripts，输入wget https://ghproxy.com/https://github.com/shufflewzc/faker2/releases/download/0.0.1/utils.zip && unzip utils.zip

如果你容器名不叫qinglong那你自己改改

**Comment by DingChang90** [comment]
https://github.com/shufflewzc/faker2/issues/25
重复了，这样解决了

**Comment by DingChang90** [comment]
> 老哥你依赖没装完，看这个：
> https://thin-hill-428.notion.site/QL-pannel-Dependent-Librai-164400378c7f4a4587f976e89aea1584
> 
> 进容器 docker exec -it qinglong bash 然后 cd qinglong/scripts，输入wget https://ghproxy.com/https://github.com/shufflewzc/faker2/releases/download/0.0.1/utils.zip && unzip utils.zip
> 
> 如果你容器名不叫qinglong那你自己改改

多谢多谢，已经解决了，自己把脚本放到对应目录下，就成功了。
