### ISSUE TITLE
jd_bean_sign.js为什么会把下载签到脚本函数给注释了啊

### ISSUE THREAD

**Issue by wjunlang** [shufflewzc/fakergone#42]
jd_bean_sign.js为什么会把下载签到脚本函数给注释了啊，如果第一次运行，没下载签到脚本就会报错了。运行不了签到，注释掉这是什么原因呢？

**Comment by wjunlang** [comment]
> jd_bean_sign.js为什么会把下载签到脚本函数给注释了啊，在37行，如果第一次运行，没下载签到脚本就会报错了。运行不了签到，注释掉这是什么原因呢？

**Comment by shufflewzc** [comment]
拉取脚本时会拉取这个文件，不需要额外下载

**Comment by wjunlang** [comment]
> 拉取脚本时会拉取这个文件，不需要额外下载

不会下载的，我看了没有签到，手动修改下载了脚本后运行才正常。

**Comment by WindStill** [comment]
> > 拉取脚本时会拉取这个文件，不需要额外下载
> 
> 不会下载的，我看了没有签到，手动修改下载了脚本后运行才正常。

要把 utils 目录放到scripts目录里
