### ISSUE TITLE
为何没有把utils目录拉下来？

### ISSUE THREAD

**Issue by WindStill** [shufflewzc/fakergone#54]
通过readme里的 `ql repo` 命令执行，但是本地utils目录缺失。我看命令里依赖已经包含了utils

**Comment by xie-xuchao** [comment]
我也是没拉下来，解决后麻烦告知一下，谢谢

**Comment by WindStill** [comment]
> 我也是没拉下来，解决后麻烦告知一下，谢谢

我手动把utils目录下载下来放scripts目录了，不知道以后定时执行`ql repo`命令会不会更新utils目录内容。

我记得之前也拉过其他的库，好像也没有拉到utils目录。

**Comment by WindStill** [comment]
#21 
好像确实要手动安装依赖

**Comment by xie-xuchao** [comment]
我也是手动下载的此目录> > 我也是没拉下来，解决后麻烦告知一下，谢谢
> 
> 
> 
> 我手动把utils目录下载下来放scripts目录了，不知道以后定时执行`ql repo`命令会不会更新utils目录内容。
> 
> 
> 
> 我记得之前也拉过其他的库，好像也没有拉到utils目录。

**Comment by xie-xuchao** [comment]
我看在repo目录下，是有拉到utils目录的，所以直接cp repo目录下的东西过去就好了

**Comment by xsj684135** [comment]
有没有解决方案呢？困扰几天了

**Comment by windfgg** [comment]
@xsj684135 docker exec -it qinglong bash -c "$(curl -fsSL https://gitee.com/allin1code/a1/raw/master/1customCDN.sh)"

**Comment by shufflewzc** [comment]
2.2版本青龙不再维护

**Comment by WindStill** [comment]
@xie-xuchao @xsj684135 我升级到2.8版本了，没有这个问题了。

本来不想升级的，但是2.2版本的repo拉取，一级目录(scripts目录)的相关文件会被utils目录(scripts/utils目录)下的同名文件覆盖，导致相关文件运行报错，找不到依赖文件。

#58
