### ISSUE TITLE
jd_bean_sign 只执行账号1

### ISSUE THREAD

**Issue by zch6348135** [shufflewzc/fakergone#56]
原因
let newContent = content.replace(/var Key = '.*'/, `var Key = '${cookie}'`);
修改为
let newContent = content.replace(/var OtherKey = `.*`/, `var OtherKey = \`[{"cookie":"${cookie}","jrBody":"${jrBody}"}]\``);

**Comment by WindStill** [comment]
添加了金东金融签到？
如果是的话，只要添加`JD_BEAN_SIGN_BODY`环境变量就好。

```
export JD_BEAN_SIGN_BODY="{\"pin\":\"ck1的pt_pin\",\"body\":\"抓包获取\"}&{\"pin\":\"ck2的pt_pin\",\"body\":\"抓包获取\"}"
```

**Comment by shufflewzc** [comment]
后续修复
