### ISSUE TITLE
领券中心签到jd_ccSign.js对某些账号签到类型不支持

### ISSUE THREAD

**Issue by lxr760** [shufflewzc/fakergone#60]
![image](https://user-images.githubusercontent.com/8476457/130416194-1d892024-bee4-46ed-9d51-67e39038ed61.png)

3个账号，前2个可以签到，但是第3个提示升级

用京东app进入签到中心发现第3个号的签到跟前2个也不一样

前2个号在京东app首页上按钮是领券     第3个号是券后9.9

**Comment by hyzaw** [comment]
正常
