### ISSUE TITLE
多合一签到：jd_bean_sign不能用

### ISSUE THREAD

**Issue by sdyby2006** [shufflewzc/fakergone#62]
其他脚本都没问题，可是多合一签到脚本运行后会显示：
已安装了依赖

开始执行 京东多合一签到 签到，请稍等...

👇👇👇👇👇👇👇👇👇👇👇签到详情👇👇👇👇👇👇👇👇👇👇👇

京东商城-超市签到失败 

京东商城-京豆Cookie失效 

京东魔方-尝试查询活动(2) 

京东现金-红包签到失败 

京东商城-闪购签到失败 

京东汽车-检查签到状态 

京东商城-摇一摇签到失败 

京东秒杀-红包查询失败 

京东商城-现金签到失败 

京东商城-转盘查询成功 

京东金融-钢镚签到失败 

京东商城-金贴签到失败 

京东金融-签肆签到失败 

京东魔方-尝试查询活动(1) 

京东转盘Cookie失效 

京东魔方-尝试查询活动(null) 

京东商城-魔方签到失败 

京东金贴-双签签到失败 

京东商城-陪伴签到失败(1)

京东商城-卡包签到失败(1)

京东商城-母婴关注店铺

京东商城-鞋靴签到失败(1)

京东商城-图书签到失败(1)

京东商城-童装关注店铺
JDJR验证中......

京东商城-小家电馆签到失败(1)

京东商城-女装签到失败(1)

京东商城-内衣关注店铺

京东商城-母婴签到成功(2)

京东商城-童装签到成功(2)

京东商城-内衣签到成功(2)
验证失败: 1
JDJR验证用时: 7.334s

京东商城-数码关注店铺

京东商城-数码签到成功(2)

京东商城-个护关注店铺

京东商城-服饰二次查询

京东商城-校园签到失败(1)

京东商城-健康关注店铺

京东商城-清洁关注店铺

京东超市关注店铺

京东商城-箱包签到失败(1)

京东商城-菜场签到失败(1)

京东拍拍-二手签到失败(1)

京东商城-个护签到成功(2)

京东商城-电竞签到失败(1)

京东商城-健康签到成功(2)

京东商城-清洁签到成功(2)

京东超市签到成功(2)

金融京豆-双签签到失败 

京东-总红包查询失败 

京东-总现金查询失败 

京东-总京豆查询失败 

京东-总金贴查询失败 

京东-总钢镚查询失败 

【签到概览】:  成功8个, 失败27个
【账号总计】:  获取失败
【其他总计】:  获取失败

京东商城-京豆: 失败, 原因: Cookie失效‼️
京东商城-超市: 失败, 原因: Cookie失效‼️
京东金融-钢镚: 失败, 原因: 未知 ⚠️
京东商城-转盘: 失败, 原因: Cookie失效‼️
京东商城-闪购: 失败, 原因: Cookie失效‼️
京东现金-红包: 失败, 原因: Cookie失效‼️
京东商城-魔方: 失败, 原因: Cookie失效‼️
京东商城-金贴: 失败, 原因: Cookie失效‼️
京东商城-现金: 失败, 原因: Cookie失效‼️
京东商城-摇摇: 失败, 原因: Cookie失效‼️
京东秒杀-红包: 失败, 原因: Cookie失效‼️
京东商城-汽车: 失败, 原因: Cookie失效‼️
京东金融-签肆: 失败, 活动未上线
京东商城-内衣: 成功, 明细: 无京豆 🐶
京东商城-卡包: 失败, 原因: Cookie失效‼️
京东商城-陪伴: 失败, 原因: Cookie失效‼️
京东商城-鞋靴: 失败, 原因: Cookie失效‼️
京东商城-童装: 成功, 明细: 无京豆 🐶
京东商城-母婴: 成功, 明细: 无京豆 🐶
京东商城-数码: 成功, 明细: 无京豆 🐶
京东商城-女装: 失败, 原因: Cookie失效‼️
京东商城-图书: 失败, 原因: Cookie失效‼️
京东商城-小家电馆: 失败, 原因: Cookie失效‼️
京东金贴-双签: 失败, 原因: Cookie失效‼️
京东商城-电竞: 失败, 原因: Cookie失效‼️
京东商城-服饰: 失败, 不含活动数据 ⚠️
京东商城-箱包: 失败, 原因: Cookie失效‼️
京东商城-校园: 失败, 原因: Cookie失效‼️
京东商城-健康: 成功, 明细: 无京豆 🐶
京东拍拍-二手: 失败, 原因: Cookie失效‼️
京东商城-清洁: 成功, 明细: 无京豆 🐶
京东商城-个护: 成功, 明细: 无京豆 🐶
京东商城-菜场: 失败, 原因: Cookie失效‼️
京东超市: 成功, 明细: 无京豆 🐶
金融京豆-双签: 失败, 原因: Cookie失效‼️

**Comment by StupidAssjeff** [comment]
> 其他脚本都没问题，可是多合一签到脚本运行后会显示：
> 
> 已安装了依赖
> 
> 
> 
> 开始执行 京东多合一签到 签到，请稍等...
> 
> 
> 
> 👇👇👇👇👇👇👇👇👇👇👇签到详情👇👇👇👇👇👇👇👇👇👇👇
> 
> 
> 
> 京东商城-超市签到失败 
> 
> 
> 
> 京东商城-京豆Cookie失效 
> 
> 
> 
> 京东魔方-尝试查询活动(2) 
> 
> 
> 
> 京东现金-红包签到失败 
> 
> 
> 
> 京东商城-闪购签到失败 
> 
> 
> 
> 京东汽车-检查签到状态 
> 
> 
> 
> 京东商城-摇一摇签到失败 
> 
> 
> 
> 京东秒杀-红包查询失败 
> 
> 
> 
> 京东商城-现金签到失败 
> 
> 
> 
> 京东商城-转盘查询成功 
> 
> 
> 
> 京东金融-钢镚签到失败 
> 
> 
> 
> 京东商城-金贴签到失败 
> 
> 
> 
> 京东金融-签肆签到失败 
> 
> 
> 
> 京东魔方-尝试查询活动(1) 
> 
> 
> 
> 京东转盘Cookie失效 
> 
> 
> 
> 京东魔方-尝试查询活动(null) 
> 
> 
> 
> 京东商城-魔方签到失败 
> 
> 
> 
> 京东金贴-双签签到失败 
> 
> 
> 
> 京东商城-陪伴签到失败(1)
> 
> 
> 
> 京东商城-卡包签到失败(1)
> 
> 
> 
> 京东商城-母婴关注店铺
> 
> 
> 
> 京东商城-鞋靴签到失败(1)
> 
> 
> 
> 京东商城-图书签到失败(1)
> 
> 
> 
> 京东商城-童装关注店铺
> 
> JDJR验证中......
> 
> 
> 
> 京东商城-小家电馆签到失败(1)
> 
> 
> 
> 京东商城-女装签到失败(1)
> 
> 
> 
> 京东商城-内衣关注店铺
> 
> 
> 
> 京东商城-母婴签到成功(2)
> 
> 
> 
> 京东商城-童装签到成功(2)
> 
> 
> 
> 京东商城-内衣签到成功(2)
> 
> 验证失败: 1
> 
> JDJR验证用时: 7.334s
> 
> 
> 
> 京东商城-数码关注店铺
> 
> 
> 
> 京东商城-数码签到成功(2)
> 
> 
> 
> 京东商城-个护关注店铺
> 
> 
> 
> 京东商城-服饰二次查询
> 
> 
> 
> 京东商城-校园签到失败(1)
> 
> 
> 
> 京东商城-健康关注店铺
> 
> 
> 
> 京东商城-清洁关注店铺
> 
> 
> 
> 京东超市关注店铺
> 
> 
> 
> 京东商城-箱包签到失败(1)
> 
> 
> 
> 京东商城-菜场签到失败(1)
> 
> 
> 
> 京东拍拍-二手签到失败(1)
> 
> 
> 
> 京东商城-个护签到成功(2)
> 
> 
> 
> 京东商城-电竞签到失败(1)
> 
> 
> 
> 京东商城-健康签到成功(2)
> 
> 
> 
> 京东商城-清洁签到成功(2)
> 
> 
> 
> 京东超市签到成功(2)
> 
> 
> 
> 金融京豆-双签签到失败 
> 
> 
> 
> 京东-总红包查询失败 
> 
> 
> 
> 京东-总现金查询失败 
> 
> 
> 
> 京东-总京豆查询失败 
> 
> 
> 
> 京东-总金贴查询失败 
> 
> 
> 
> 京东-总钢镚查询失败 
> 
> 
> 
> 
> 
> 【签到概览】:  成功8个, 失败27个
> 
> 【账号总计】:  获取失败
> 
> 【其他总计】:  获取失败
> 
> 
> 
> 京东商城-京豆: 失败, 原因: Cookie失效‼️
> 
> 京东商城-超市: 失败, 原因: Cookie失效‼️
> 
> 京东金融-钢镚: 失败, 原因: 未知 ⚠️
> 
> 京东商城-转盘: 失败, 原因: Cookie失效‼️
> 
> 京东商城-闪购: 失败, 原因: Cookie失效‼️
> 
> 京东现金-红包: 失败, 原因: Cookie失效‼️
> 
> 京东商城-魔方: 失败, 原因: Cookie失效‼️
> 
> 京东商城-金贴: 失败, 原因: Cookie失效‼️
> 
> 京东商城-现金: 失败, 原因: Cookie失效‼️
> 
> 京东商城-摇摇: 失败, 原因: Cookie失效‼️
> 
> 京东秒杀-红包: 失败, 原因: Cookie失效‼️
> 
> 京东商城-汽车: 失败, 原因: Cookie失效‼️
> 
> 京东金融-签肆: 失败, 活动未上线
> 
> 京东商城-内衣: 成功, 明细: 无京豆 🐶
> 
> 京东商城-卡包: 失败, 原因: Cookie失效‼️
> 
> 京东商城-陪伴: 失败, 原因: Cookie失效‼️
> 
> 京东商城-鞋靴: 失败, 原因: Cookie失效‼️
> 
> 京东商城-童装: 成功, 明细: 无京豆 🐶
> 
> 京东商城-母婴: 成功, 明细: 无京豆 🐶
> 
> 京东商城-数码: 成功, 明细: 无京豆 🐶
> 
> 京东商城-女装: 失败, 原因: Cookie失效‼️
> 
> 京东商城-图书: 失败, 原因: Cookie失效‼️
> 
> 京东商城-小家电馆: 失败, 原因: Cookie失效‼️
> 
> 京东金贴-双签: 失败, 原因: Cookie失效‼️
> 
> 京东商城-电竞: 失败, 原因: Cookie失效‼️
> 
> 京东商城-服饰: 失败, 不含活动数据 ⚠️
> 
> 京东商城-箱包: 失败, 原因: Cookie失效‼️
> 
> 京东商城-校园: 失败, 原因: Cookie失效‼️
> 
> 京东商城-健康: 成功, 明细: 无京豆 🐶
> 
> 京东拍拍-二手: 失败, 原因: Cookie失效‼️
> 
> 京东商城-清洁: 成功, 明细: 无京豆 🐶
> 
> 京东商城-个护: 成功, 明细: 无京豆 🐶
> 
> 京东商城-菜场: 失败, 原因: Cookie失效‼️
> 
> 京东超市: 成功, 明细: 无京豆 🐶
> 
> 金融京豆-双签: 失败, 原因: Cookie失效‼️
> 
> 

What the fuck is this

**Comment by Jiaswa** [comment]
同，这几天一直不行
