### ISSUE TITLE
采用一键脚本后无法内部互助

### ISSUE THREAD

**Issue by Pessimisticc** [shufflewzc/fakergone#65]
采用一键脚本后无法内部互助，后将task_before.sh改回其原作者 # Build 20210817-001版本后恢复正常

**Comment by shufflewzc** [comment]
一键脚本需要选择本仓库互助才可以的

**Comment by Pessimisticc** [comment]
都是拉你的库的，task_before.sh最新版本的有问题

**Comment by shufflewzc** [comment]
@yuanlang1 是从低版本升级到高版本吗？

**Comment by Pessimisticc** [comment]
我是全新安装的，# Build 20210822-001这个版本无法写入互助码，换成旧的 Build 20210817-001菜开始内部助力的

**Comment by lovehuiping** [comment]
> 我是全新安装的，# Build 20210822-001这个版本无法写入互助码，换成旧的 Build 20210817-001菜开始内部助力的

你好. 同样的问题 请问0817的在哪里下载到
