### ISSUE TITLE
jd_bean_sign.js问题

### ISSUE THREAD

**Issue by kokpk** [shufflewzc/fakergone#67]
刚开始运行会显示有几个Cookie，执行时候就会提示脚本终止, 未获取Cookie ‼️。ck正常在其他脚本中正常。

**Comment by qingfengfenga** [comment]
请问解决了吗，我也有这个问题

**Comment by kokpk** [comment]
> 好像解决了，我也有这个问题

解决了，更新最新的。记得更新拉库命令

**Comment by qingfengfenga** [comment]
我这边更新了仓库还是不行，可以贴一下操作方法吗，感谢

**Comment by qingfengfenga** [comment]
在README上找到新命令了，更新了一下可以了，感谢！
`ql repo https://ghproxy.com/https://github.com/shufflewzc/faker2.git "jd_|jx_|gua_|jddj_|getJDCookie" "activity|backUp" "^jd[^_]|USER|utils|ZooFaker_Necklace.js|JDJRValidator_Pure|sign_graphics_validate"`

**Comment by qingfengfenga** [comment]
在README上找到新命令了，更新了一下可以了，感谢！
`ql repo https://ghproxy.com/https://github.com/shufflewzc/faker2.git "jd_|jx_|gua_|jddj_|getJDCookie" "activity|backUp" "^jd[^_]|USER|utils|ZooFaker_Necklace.js|JDJRValidator_Pure|sign_graphics_validate"`
