### ISSUE TITLE
想引用文件，不过关于JS文件中相对路径的参数问题希望能重新声明下

### ISSUE THREAD

**Issue by flyhigherpi** [shufflewzc/fakergone#68]
比如jd_bean_sign.js

原语句：let JD_DailyBonusPath = "./utils/JD_DailyBonus.js";
并不能取得文件路径；
修改后如下

const path = require('path');
let JD_DailyBonusPath = path.resolve(__dirname,'./utils/JD_DailyBonus.js');
let outPutUrl = path.resolve(__dirname,'./utils');

**Comment by shufflewzc** [comment]
你是在什么环境下运行呢

**Comment by flyhigherpi** [comment]
> 你是在什么环境下运行呢

华硕路由entware环境下用nodejs跑的。自己把这段路径改了之后就不会出现文件not found了

**Comment by iOSleep** [comment]
#87 可能和这个有关？

**Comment by flyhigherpi** [comment]
> #87 可能和这个有关？

今天对比了代码，发现之前jd_bean_sign.js有一次的版本，
// 下载最新代码
  // await downFile();
未注释，然后会下载一份JD_DailyBonus.js 存放于路由的/root/utils/ 目录。 
然后脚本就可以签到了。
这个相对路径识别真迷
