### ISSUE TITLE
jd_try的trialPrice的一点疑惑

### ISSUE THREAD

**Issue by RockZhou8** [shufflewzc/fakergone#86]
```    // 试用价格，高于这个价格都不会试用，小于等于才会试用
    trialPrice: 10,
```
这里的价格过滤是不是应该过滤低价的？

**Comment by X1a0He** [comment]
> ```
>     trialPrice: 10,
> ```
> 
> 这里的价格过滤是不是应该过滤低价的？

你好，我是修复的作者，由于这个脚本问题有点多，今天修复比较频繁，所以可能Faker2没有及时拉取新的脚本，你可以在我的库中找到新加的代码，脚本中jdPrice应该是你说的过滤最低价，详情已经写在注释上了

**Comment by X1a0He** [comment]
> ```
>     trialPrice: 10,
> ```
> 
> 这里的价格过滤是不是应该过滤低价的？

https://github.com/X1a0He/jd_scripts_fixed/blob/main/jd_try_xh.js

**Comment by RockZhou8** [comment]
> > ```
> >     trialPrice: 10,
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这里的价格过滤是不是应该过滤低价的？
> 
> https://github.com/X1a0He/jd_scripts_fixed/blob/main/jd_try_xh.js

哇 原来修复了！
谢谢大佬，感谢！
