### ISSUE TITLE
京东极速版运行异常

### ISSUE THREAD

**Issue by iskycc** [shufflewzc/fakergone#89]
看到日志显示，好几天都只运行了前两个号，后面的号都没有运行

**Comment by iskycc** [comment]
shufflewzc_faker2_jd_speed_sign.js

**Comment by iskycc** [comment]
手动执行正常

**Comment by Hyper-Beast** [comment]
设置所有账号并发运行
task shufflewzc_faker2_jd_speed_sign.js conc JD_COOKIE

**Comment by xx668888** [comment]
> 设置所有账号并发运行
> task shufflewzc_faker2_jd_speed_sign.js conc JD_COOKIE

我加了这个  只能识别一个ck啊，其他的账号 都不执行；
![image](https://user-images.githubusercontent.com/41692185/134602645-3e006556-72e3-4c2f-aff4-81cade4d040c.png)
