### ISSUE TITLE
shufflewzc_faker2_jd_bean_home.js 死循环

### ISSUE THREAD

**Issue by Jiaswa** [shufflewzc/fakergone#91]
去做[猜你喜欢的商品]undefined
完成任务，获得+undefined成长值
去做[猜你喜欢的商品]undefined
完成任务，获得+undefined成长值
去做[猜你喜欢的商品]undefined
完成任务，获得+undefined成长值
去做[猜你喜欢的商品]undefined
完成任务，获得+undefined成长值
去做[猜你喜欢的商品]undefined
完成任务，获得+undefined成长值
去做[猜你喜欢的商品]undefined
完成任务，获得+undefined成长值
去做[猜你喜欢的商品]undefined
完成任务，获得+undefined成长值
去做[猜你喜欢的商品]undefined
完成任务，获得+undefined成长值
去做[猜你喜欢的商品]undefined
完成任务，获得+undefined成长值

**Comment by windfgg** [comment]
@Jiaswa 只负责收集脚本 不负责修改脚本
